# -*- mode: shell-script -*-
export DOTFILES_DIR=$HOME/src/dotfiles

export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
unset LC_ALL
export HISTFILESIZE=10000
export HISTSIZE=10000
export PROMPT_COMMAND='history -a'
shopt -s histappend

# shell prompt setup
function __git_ps1()
{
    local b="$(git symbolic-ref HEAD 2>/dev/null)";
    if [ -n "$b" ]; then
        printf " (%s)" "${b##refs/heads/}";
    fi
}

export PS1='\W \u\[\e[01;37m\]:`[[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo "\[\e[31m\]" || echo "\[\e[32m\]"`$(__git_ps1 "(%s)\[\e[00m\]")\[\e[00m\]\$ '

# EDITOR + terminal setup
export TERM=xterm-256color
export EDITOR="emacs"
export ALTERNATE_EDITOR="emacs"
# source aliases
source $DOTFILES_DIR/bash/aliases

# Global variables
export GITHUB_LOGIN="riethmayer"
export AWS_ENV="production"
export ORGANIZATION_GITHUB_LOGIN="bonusboxme"

## for linking GH stuff
export GITHUB_PROJECTS_PATH=$HOME/github

## for bonusbox stuff
export PROJECT_BASE=$HOME/bonusbox/projects
export BONUSBOX_BI_PATH=$PROJECT_BASE/bi
## homebrew
export PATH="/usr/local/sbin:/usr/local/bin:$PATH"

## my scripts
export PATH=$HOME/bin:$PATH

# me secretz
[ ! -d $HOME/src/secret ] && source $HOME/src/secret/environment.sh

## bonusbox projects
export PATH=$PROJECT_BASE/bb/bin:$PATH
[ -d $PROJECT_BASE/bb ] && eval "$($PROJECT_BASE/bb/bin/bb init -)"

[ -d $PROJECT_BASE/bb ] && source $PROJECT_BASE/bb/credentials.sh
# travis setup
[ -f $HOME/.travis ] && source $HOME/.travis/travis.sh

## ANSIBLE
export PATH=$GITHUB_PROJECTS_PATH/ansible/bin:$PATH
export PYTHONPATH=$GITHUB_PROJECTS_PATH/ansible/lib:$PYTHONPATH
export MANPATH=$GITHUB_PROJECTS_PATH/ansible/docs/man:$MANPATH

## NPM
export PATH=/usr/local/share/npm/bin:$PATH

## Yarn
export PATH="$PATH:`yarn global bin`"

## RVM needs to be at the end or it complaints
# export PATH="$PATH:$HOME/.rvm/bin"
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# RBENV
eval "$(rbenv init -)"

# Java
export JAVA_HOME=$(/usr/libexec/java_home)

# openssl (don't export by default)
export PATH="/usr/local/opt/openssl/bin:$PATH"
export CPPFLAGS="-I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include"
export LDFLAGS="-L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib"
